rtx.upscalerType = 0
rtx.resolutionScale = 1.0
rtx.texturemanager.samplerFeedbackEnable = False
rtx.texturemanager.neverDowngradeTextures = False
rtx.vertexColorStrength = 0.0
rtx.skyBoxTextures = 0x9864371B47BAC786, 0x94AB937384DB5A18, 0x83597CCA5EF25256, 0x84395323BBBB705A
